import { StyleSheet } from "react-native";
import { responsiveFontSize, responsiveSize } from "../../../utils/responsive";

export const incidentsTableStyles = StyleSheet.create({
  container: {
    padding: responsiveSize(18),
    backgroundColor: "#ffffff",
    borderRadius: responsiveSize(12),
    borderWidth: 1,
    borderColor: "#e3bebe",
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  heading: {
    fontSize: responsiveFontSize(18),
    fontWeight: "700",
    marginBottom: responsiveSize(14),
    color: "#161d21",
  },
  filtersRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: responsiveSize(8),
    alignItems: "center",
    marginBottom: responsiveSize(14),
  },
  input: {
    borderWidth: 1,
    borderColor: "#e3bebe",
    backgroundColor: "#ffffff",
    borderRadius: responsiveSize(8),
    paddingHorizontal: responsiveSize(10),
    paddingVertical: responsiveSize(9),
    fontSize: responsiveFontSize(14),
    color: "#161d21",
    minWidth: responsiveSize(138),
  },
  searchInput: {
    minWidth: responsiveSize(220),
    flexGrow: 1,
  },
  filterButton: {
    borderWidth: 1,
    borderColor: "#e3bebe",
    borderRadius: responsiveSize(999),
    backgroundColor: "#eef4fa",
    paddingHorizontal: responsiveSize(12),
    paddingVertical: responsiveSize(9),
  },
  filterButtonText: {
    fontSize: responsiveFontSize(13),
    color: "#5b4040",
    fontWeight: "700",
  },
  primaryButton: {
    backgroundColor: "#c41c3b",
    borderRadius: responsiveSize(999),
    paddingHorizontal: responsiveSize(14),
    paddingVertical: responsiveSize(10),
  },
  primaryButtonText: {
    color: "#ffffff",
    fontWeight: "800",
    fontSize: responsiveFontSize(13),
  },
  secondaryButton: {
    backgroundColor: "#eef4fa",
    borderWidth: 1,
    borderColor: "#e3bebe",
    borderRadius: responsiveSize(999),
    paddingHorizontal: responsiveSize(14),
    paddingVertical: responsiveSize(9),
  },
  secondaryButtonText: {
    color: "#5b4040",
    fontWeight: "800",
    fontSize: responsiveFontSize(13),
  },
  table: {
    minWidth: responsiveSize(1130),
  },
  mobileList: {
    gap: responsiveSize(10),
  },
  mobileCard: {
    backgroundColor: "#eef4fa",
    borderWidth: 1,
    borderColor: "#e3bebe",
    borderRadius: responsiveSize(10),
    padding: responsiveSize(12),
    gap: responsiveSize(5),
  },
  mobileCardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: responsiveSize(4),
  },
  mobileTitle: {
    fontSize: responsiveFontSize(14),
    fontWeight: "800",
    color: "#161d21",
    flexShrink: 1,
    marginRight: responsiveSize(8),
  },
  mobileMeta: {
    fontSize: responsiveFontSize(13),
    color: "#5b4040",
    fontWeight: "600",
  },
  tableHeader: {
    backgroundColor: "#eef4fa",
    borderRadius: responsiveSize(8),
  },
  tableRow: {
    flexDirection: "row",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: "#e3bebe",
    minHeight: responsiveSize(52),
    paddingVertical: responsiveSize(7),
  },
  cell: {
    fontSize: responsiveFontSize(13),
    color: "#161d21",
    paddingHorizontal: responsiveSize(10),
  },
  headerCell: {
    fontWeight: "800",
    color: "#5b4040",
    textTransform: "uppercase",
  },
  cellId: {
    width: responsiveSize(120),
  },
  cellType: {
    width: responsiveSize(80),
  },
  cellLocation: {
    width: responsiveSize(190),
  },
  cellMethod: {
    width: responsiveSize(150),
  },
  cellTime: {
    width: responsiveSize(120),
  },
  cellDate: {
    width: responsiveSize(140),
  },
  cellStatus: {
    width: responsiveSize(160),
  },
  cellActions: {
    width: responsiveSize(180),
  },
  statusBadge: {
    color: "#ffffff",
    fontWeight: "800",
    textTransform: "lowercase",
    paddingVertical: responsiveSize(3),
    paddingHorizontal: responsiveSize(9),
    borderRadius: responsiveSize(999),
    overflow: "hidden",
    alignSelf: "flex-start",
    fontSize: responsiveFontSize(12),
  },
  actionsCell: {
    flexDirection: "row",
    gap: responsiveSize(8),
  },
  editButton: {
    backgroundColor: "#236580",
    borderRadius: responsiveSize(999),
    paddingHorizontal: responsiveSize(12),
    paddingVertical: responsiveSize(7),
  },
  deleteButton: {
    backgroundColor: "#9d0028",
    borderRadius: responsiveSize(999),
    paddingHorizontal: responsiveSize(12),
    paddingVertical: responsiveSize(7),
  },
  actionButtonText: {
    color: "#ffffff",
    fontSize: responsiveFontSize(12),
    fontWeight: "800",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(22, 29, 33, 0.45)",
    justifyContent: "center",
    alignItems: "center",
    padding: responsiveSize(14),
  },
  modalCard: {
    width: "100%",
    maxWidth: responsiveSize(520),
    borderRadius: responsiveSize(12),
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#e3bebe",
    padding: responsiveSize(16),
    gap: responsiveSize(10),
  },
  pickerCard: {
    width: "100%",
    maxWidth: responsiveSize(420),
    maxHeight: responsiveSize(340),
    borderRadius: responsiveSize(12),
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#e3bebe",
    padding: responsiveSize(16),
    gap: responsiveSize(10),
  },
  datePickerCard: {
    width: "100%",
    maxWidth: responsiveSize(420),
    borderRadius: responsiveSize(12),
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#e3bebe",
    padding: responsiveSize(16),
    gap: responsiveSize(10),
  },
  pickerOption: {
    borderWidth: 1,
    borderColor: "#e3bebe",
    borderRadius: responsiveSize(8),
    backgroundColor: "#eef4fa",
    paddingVertical: responsiveSize(10),
    paddingHorizontal: responsiveSize(10),
    marginBottom: responsiveSize(8),
  },
  pickerOptionText: {
    fontSize: responsiveFontSize(14),
    color: "#161d21",
    textTransform: "capitalize",
    fontWeight: "700",
  },
  modalTitle: {
    fontSize: responsiveFontSize(18),
    fontWeight: "700",
    color: "#161d21",
    marginBottom: responsiveSize(6),
  },
  inlineSelectRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: responsiveSize(8),
  },
  modalActions: {
    marginTop: responsiveSize(6),
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: responsiveSize(8),
  },
  chip: {
    fontSize: responsiveFontSize(12),
    fontWeight: "800",
  },
});
