import { StyleSheet } from "react-native";
import { responsiveFontSize, responsiveSize } from "../../../utils/responsive";

export const operationsProfileStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f4faff",
    paddingBottom: responsiveSize(20),
  },
  profileHeader: {
    alignItems: "center",
    paddingVertical: responsiveSize(22),
    backgroundColor: "#ffffff",
    marginBottom: responsiveSize(16),
    borderWidth: 1,
    borderColor: "#e3bebe",
    borderRadius: responsiveSize(12),
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  profilePictureContainer: {
    marginBottom: responsiveSize(12),
  },
  profilePicture: {
    width: responsiveSize(120),
    height: responsiveSize(120),
    borderRadius: responsiveSize(60),
    borderWidth: 3,
    borderColor: "#9d0028",
  },
  imageActionButton: {
    borderWidth: 1,
    borderColor: "#e3bebe",
    backgroundColor: "#eef4fa",
    borderRadius: responsiveSize(999),
    paddingHorizontal: responsiveSize(14),
    paddingVertical: responsiveSize(8),
    marginBottom: responsiveSize(10),
  },
  imageActionButtonText: {
    color: "#9d0028",
    fontSize: responsiveFontSize(12),
    fontWeight: "800",
  },
  profileName: {
    fontSize: responsiveFontSize(22),
    fontWeight: "700",
    color: "#161d21",
    marginBottom: responsiveSize(4),
  },
  profileRank: {
    fontSize: responsiveFontSize(14),
    fontWeight: "800",
    color: "#9d0028",
    marginBottom: responsiveSize(4),
  },
  profileStation: {
    fontSize: responsiveFontSize(12),
    color: "#5b4040",
    marginBottom: responsiveSize(8),
    textAlign: "center",
    paddingHorizontal: responsiveSize(12),
  },
  profileId: {
    fontSize: responsiveFontSize(11),
    color: "#5b4040",
    fontWeight: "700",
    letterSpacing: 0.6,
  },
  section: {
    marginBottom: responsiveSize(16),
  },
  sectionTitle: {
    fontSize: responsiveFontSize(14),
    fontWeight: "800",
    color: "#161d21",
    marginBottom: responsiveSize(10),
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  infoCard: {
    backgroundColor: "#ffffff",
    borderRadius: responsiveSize(12),
    paddingVertical: responsiveSize(8),
    borderWidth: 1,
    borderColor: "#e3bebe",
  },
  infoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: responsiveSize(16),
    paddingVertical: responsiveSize(12),
  },
  infoLabel: {
    fontSize: responsiveFontSize(13),
    fontWeight: "800",
    color: "#5b4040",
  },
  infoValue: {
    fontSize: responsiveFontSize(13),
    fontWeight: "600",
    color: "#161d21",
    flex: 1,
    textAlign: "right",
    marginLeft: responsiveSize(12),
  },
  infoValueLink: {
    fontSize: responsiveFontSize(13),
    fontWeight: "700",
    color: "#9d0028",
    flex: 1,
    textAlign: "right",
    marginLeft: responsiveSize(12),
  },
  divider: {
    height: 1,
    backgroundColor: "#e3bebe",
    opacity: 0.7,
    marginHorizontal: responsiveSize(16),
  },
  formField: {
    paddingHorizontal: responsiveSize(16),
    paddingVertical: responsiveSize(12),
    gap: responsiveSize(8),
  },
  formInput: {
    borderWidth: 1,
    borderColor: "#e3bebe",
    borderRadius: responsiveSize(8),
    paddingHorizontal: responsiveSize(12),
    paddingVertical: responsiveSize(10),
    fontSize: responsiveFontSize(13),
    color: "#161d21",
    backgroundColor: "#eef4fa",
  },
  saveButton: {
    marginTop: responsiveSize(12),
    backgroundColor: "#c41c3b",
    borderRadius: responsiveSize(999),
    paddingVertical: responsiveSize(12),
    alignItems: "center",
  },
  saveButtonText: {
    color: "#ffffff",
    fontSize: responsiveFontSize(14),
    fontWeight: "800",
  },
  statsGrid: {
    flexDirection: "row",
    gap: responsiveSize(12),
    justifyContent: "space-between",
  },
  statCard: {
    flex: 1,
    backgroundColor: "#ffffff",
    borderRadius: responsiveSize(12),
    paddingVertical: responsiveSize(16),
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#e3bebe",
  },
  statValue: {
    fontSize: responsiveFontSize(28),
    fontWeight: "800",
    color: "#9d0028",
    marginBottom: responsiveSize(4),
  },
  statLabel: {
    fontSize: responsiveFontSize(11),
    color: "#5b4040",
    fontWeight: "700",
    textAlign: "center",
  },
  certContainer: {
    flexDirection: "column",
    gap: responsiveSize(8),
  },
  certBadge: {
    backgroundColor: "#eef4fa",
    borderLeftWidth: 4,
    borderLeftColor: "#9d0028",
    paddingVertical: responsiveSize(10),
    paddingHorizontal: responsiveSize(12),
    borderRadius: responsiveSize(8),
  },
  certText: {
    fontSize: responsiveFontSize(13),
    fontWeight: "800",
    color: "#5b4040",
  },
  settingsCard: {
    backgroundColor: "#ffffff",
    borderRadius: responsiveSize(12),
    paddingVertical: responsiveSize(8),
    borderWidth: 1,
    borderColor: "#e3bebe",
  },
  settingRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: responsiveSize(16),
    paddingVertical: responsiveSize(12),
  },
  settingLabel: {
    fontSize: responsiveFontSize(13),
    fontWeight: "800",
    color: "#161d21",
  },
  bottomPadding: {
    height: responsiveSize(20),
  },
});
