import { StyleSheet } from "react-native";
import { responsiveFontSize, responsiveSize } from "../../../utils/responsive";

const colors = {
  background: "#f4faff",
  surface: "#ffffff",
  surfaceLow: "#eef4fa",
  surfaceHigh: "#e2e9ef",
  surfaceHighest: "#dce3e9",
  primary: "#9d0028",
  primaryContainer: "#c41c3b",
  secondary: "#236580",
  outline: "#e3bebe",
  text: "#161d21",
  muted: "#5b4040",
  inverse: "#ffffff",
};

export const reportsScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  content: {
    paddingBottom: responsiveSize(28),
    gap: responsiveSize(16),
  },
  pageHeader: {
    gap: responsiveSize(6),
  },
  pageTitle: {
    color: colors.text,
    fontSize: responsiveFontSize(24),
    fontWeight: "700",
    lineHeight: responsiveSize(30),
  },
  pageSubtitle: {
    color: colors.muted,
    fontSize: responsiveFontSize(15),
    fontWeight: "500",
    lineHeight: responsiveSize(21),
  },
  card: {
    backgroundColor: colors.surface,
    borderColor: colors.outline,
    borderRadius: responsiveSize(12),
    borderWidth: 1,
    padding: responsiveSize(18),
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  cardHeader: {
    alignItems: "flex-start",
    flexDirection: "row",
    justifyContent: "space-between",
    gap: responsiveSize(12),
    marginBottom: responsiveSize(18),
  },
  eyebrow: {
    color: colors.muted,
    fontSize: responsiveFontSize(10),
    fontWeight: "700",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  cardTitle: {
    color: colors.text,
    fontSize: responsiveFontSize(18),
    fontWeight: "700",
    lineHeight: responsiveSize(24),
    marginTop: responsiveSize(4),
  },
  metricBlock: {
    alignItems: "flex-end",
  },
  metricValue: {
    color: colors.primary,
    fontSize: responsiveFontSize(24),
    fontWeight: "800",
    lineHeight: responsiveSize(30),
  },
  metricLabel: {
    color: colors.muted,
    fontSize: responsiveFontSize(10),
    fontWeight: "600",
  },
  chartWrap: {
    backgroundColor: colors.surfaceLow,
    borderRadius: responsiveSize(12),
    height: responsiveSize(256),
    overflow: "hidden",
    paddingTop: responsiveSize(12),
  },
  chartDays: {
    bottom: responsiveSize(8),
    flexDirection: "row",
    justifyContent: "space-between",
    left: responsiveSize(16),
    position: "absolute",
    right: responsiveSize(16),
  },
  chartDay: {
    color: colors.muted,
    fontSize: responsiveFontSize(10),
    fontWeight: "700",
    letterSpacing: 1,
  },
  allocationList: {
    gap: responsiveSize(14),
    marginTop: responsiveSize(18),
  },
  allocationItem: {
    gap: responsiveSize(6),
  },
  allocationHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  allocationLabel: {
    color: colors.text,
    fontSize: responsiveFontSize(12),
    fontWeight: "700",
  },
  progressTrack: {
    backgroundColor: colors.surfaceHigh,
    borderRadius: responsiveSize(999),
    height: responsiveSize(10),
    overflow: "hidden",
  },
  progressFill: {
    borderRadius: responsiveSize(999),
    height: "100%",
  },
  commandNote: {
    backgroundColor: colors.surfaceLow,
    borderColor: colors.outline,
    borderRadius: responsiveSize(8),
    borderWidth: 1,
    marginTop: responsiveSize(18),
    padding: responsiveSize(12),
  },
  commandNoteText: {
    color: colors.muted,
    fontSize: responsiveFontSize(12),
    fontStyle: "italic",
    fontWeight: "500",
    lineHeight: responsiveSize(18),
  },
  riskGrid: {
    flexDirection: "row",
    gap: responsiveSize(12),
    marginTop: responsiveSize(18),
    marginBottom: responsiveSize(18),
  },
  riskTile: {
    alignItems: "center",
    backgroundColor: colors.surfaceLow,
    borderColor: colors.outline,
    borderRadius: responsiveSize(12),
    borderWidth: 1,
    flex: 1,
    minHeight: responsiveSize(148),
    padding: responsiveSize(14),
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 5,
    elevation: 1,
  },
  riskTileHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: responsiveSize(6),
    justifyContent: "center",
    marginBottom: responsiveSize(12),
  },
  riskLabel: {
    color: colors.secondary,
    flexShrink: 1,
    fontSize: responsiveFontSize(12),
    fontWeight: "700",
  },
  riskValue: {
    color: colors.text,
    fontSize: responsiveFontSize(28),
    fontWeight: "700",
    lineHeight: responsiveSize(34),
    marginBottom: responsiveSize(8),
  },
  riskStatus: {
    color: colors.muted,
    fontSize: responsiveFontSize(10),
    fontWeight: "800",
    letterSpacing: 0.8,
    textAlign: "center",
    textTransform: "uppercase",
  },
  riskStatusCritical: {
    color: colors.primary,
  },
  secondaryAction: {
    alignItems: "center",
    backgroundColor: colors.secondary,
    borderRadius: responsiveSize(999),
    flexDirection: "row",
    gap: responsiveSize(8),
    justifyContent: "center",
    minHeight: responsiveSize(46),
    paddingHorizontal: responsiveSize(18),
  },
  secondaryActionText: {
    color: colors.inverse,
    fontSize: responsiveFontSize(14),
    fontWeight: "800",
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  synthesisCard: {
    alignItems: "center",
    borderStyle: "dashed",
    gap: responsiveSize(10),
  },
  synthesisIcon: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderColor: colors.outline,
    borderRadius: responsiveSize(999),
    borderWidth: 1,
    height: responsiveSize(64),
    justifyContent: "center",
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    width: responsiveSize(64),
    elevation: 3,
  },
  synthesisText: {
    color: colors.muted,
    fontSize: responsiveFontSize(15),
    fontWeight: "500",
    lineHeight: responsiveSize(21),
    maxWidth: responsiveSize(320),
    textAlign: "center",
  },
  primaryAction: {
    alignItems: "center",
    alignSelf: "stretch",
    backgroundColor: colors.primaryContainer,
    borderRadius: responsiveSize(999),
    justifyContent: "center",
    minHeight: responsiveSize(46),
    marginTop: responsiveSize(4),
    paddingHorizontal: responsiveSize(18),
  },
  primaryActionText: {
    color: colors.inverse,
    fontSize: responsiveFontSize(14),
    fontWeight: "800",
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  reportsSection: {
    gap: responsiveSize(12),
  },
  reportsHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: responsiveSize(12),
    justifyContent: "space-between",
  },
  viewAllButton: {
    alignItems: "center",
    flexDirection: "row",
    flexShrink: 0,
    gap: responsiveSize(2),
  },
  viewAllText: {
    color: colors.primary,
    fontSize: responsiveFontSize(12),
    fontWeight: "800",
  },
  reportRow: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderColor: colors.outline,
    borderRadius: responsiveSize(12),
    borderWidth: 1,
    flexDirection: "row",
    gap: responsiveSize(14),
    minHeight: responsiveSize(76),
    padding: responsiveSize(14),
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 1,
  },
  pdfIconBox: {
    alignItems: "center",
    backgroundColor: colors.surfaceLow,
    borderRadius: responsiveSize(8),
    height: responsiveSize(48),
    justifyContent: "center",
    width: responsiveSize(48),
  },
  reportTextBlock: {
    flex: 1,
    minWidth: 0,
  },
  reportName: {
    color: colors.text,
    fontSize: responsiveFontSize(14),
    fontWeight: "800",
  },
  reportMeta: {
    color: colors.muted,
    fontSize: responsiveFontSize(12),
    fontWeight: "500",
    marginTop: responsiveSize(2),
  },
  commandFooter: {
    borderColor: colors.surfaceHighest,
    borderTopWidth: 1,
    color: colors.muted,
    fontSize: responsiveFontSize(10),
    fontWeight: "700",
    letterSpacing: 1,
    opacity: 0.55,
    paddingTop: responsiveSize(20),
    textAlign: "center",
    textTransform: "uppercase",
  },
});
