// styles/auth/login.ts
import { Dimensions, StyleSheet } from "react-native";
import { responsiveFontSize, responsiveSize } from "../../utils/responsive";

const { height, width } = Dimensions.get("window");
const cardWidth = Math.min(width - responsiveSize(28), 420);

export const loginStyles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: "#f4faff",
  },
  splashScreen: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 5,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    backgroundColor: "#f4faff",
  },
  dotGrid: {
    ...StyleSheet.absoluteFillObject,
    flexDirection: "row",
    flexWrap: "wrap",
    opacity: 0.85,
  },
  dot: {
    width: 2,
    height: 2,
    borderRadius: 1,
    marginHorizontal: 11,
    marginVertical: 11,
    backgroundColor: "#dce3e9",
  },
  splashLogoWrap: {
    width: Math.min(width * 0.7, 500),
    height: Math.min(width * 0.7, 500),
    alignItems: "center",
    justifyContent: "center",
  },
  splashLogo: {
    width: "100%",
    height: "100%",
  },
  splashKicker: {
    marginTop: responsiveSize(24),
    color: "#5b4040",
    fontSize: responsiveFontSize(12),
    fontWeight: "700",
    letterSpacing: 2.4,
    opacity: 0.8,
    textAlign: "center",
    textTransform: "uppercase",
  },
  versionText: {
    position: "absolute",
    bottom: responsiveSize(32),
    color: "#8f6f70",
    fontSize: responsiveFontSize(12),
    fontWeight: "500",
    opacity: 0.45,
  },
  loginScreen: {
    flex: 1,
    backgroundColor: "#f4faff",
  },
  meshBackground: {
    ...StyleSheet.absoluteFillObject,
    overflow: "hidden",
  },
  meshGlow: {
    position: "absolute",
    width: width * 0.75,
    height: width * 0.75,
    borderRadius: width,
    opacity: 0.18,
  },
  meshGlowPrimaryTop: {
    top: -width * 0.35,
    left: -width * 0.35,
    backgroundColor: "#ffb3b4",
  },
  meshGlowSecondaryTop: {
    top: -width * 0.25,
    right: -width * 0.3,
    backgroundColor: "#92cfee",
  },
  meshGlowPrimaryBottom: {
    bottom: -width * 0.32,
    right: -width * 0.25,
    backgroundColor: "#ffdada",
  },
  meshGlowSecondaryBottom: {
    bottom: -width * 0.3,
    left: -width * 0.28,
    backgroundColor: "#c0e8ff",
  },
  safeArea: {
    flex: 1,
  },
  keyboardView: {
    flex: 1,
  },
  contentContainer: {
    minHeight: height,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: responsiveSize(14),
    paddingTop: responsiveSize(24),
    paddingBottom: responsiveSize(24),
  },
  brandSection: {
    width: cardWidth,
    alignItems: "center",
    marginBottom: responsiveSize(20),
  },
  logoContainer: {
    width: "100%",
    height: responsiveSize(210),
    alignItems: "center",
    justifyContent: "flex-end",
    overflow: "visible",
  },
  bouncingLogo: {
    width: "70%",
    maxWidth: 300,
    aspectRatio: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  logoImage: {
    width: "100%",
    height: "100%",
    opacity: 0.92,
  },
  splashLayer: {
    position: "absolute",
    bottom: responsiveSize(4),
    left: 0,
    right: 0,
    height: responsiveSize(42),
    alignItems: "center",
    justifyContent: "flex-end",
  },
  ripple: {
    position: "absolute",
    bottom: responsiveSize(2),
    width: 160,
    height: 40,
    borderWidth: 2,
    borderColor: "#3b82f6",
    borderRadius: 80,
  },
  droplet: {
    position: "absolute",
    bottom: responsiveSize(14),
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#3b82f6",
  },
  titleBlock: {
    alignItems: "center",
  },
  titleMark: {
    width: 48,
    height: 4,
    borderRadius: 999,
    marginBottom: responsiveSize(16),
    backgroundColor: "#c41c3b",
    opacity: 0.2,
  },
  title: {
    color: "#161d21",
    fontSize: responsiveFontSize(24),
    fontWeight: "700",
    lineHeight: responsiveFontSize(30),
    textAlign: "center",
  },
  subtitle: {
    maxWidth: 280,
    marginTop: responsiveSize(8),
    color: "#5b4040",
    fontSize: responsiveFontSize(14),
    fontWeight: "500",
    lineHeight: responsiveFontSize(20),
    opacity: 0.72,
    textAlign: "center",
  },
  formCard: {
    width: cardWidth,
    padding: responsiveSize(24),
    gap: responsiveSize(16),
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.72)",
    borderRadius: responsiveSize(28),
    backgroundColor: "rgba(255, 255, 255, 0.78)",
    shadowColor: "#c41c3b",
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.08,
    shadowRadius: 28,
    elevation: 7,
  },
  inputGroup: {
    gap: responsiveSize(8),
  },
  passwordLabelRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
  },
  label: {
    color: "#5b4040",
    fontSize: responsiveFontSize(13),
    fontWeight: "700",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  recoveryText: {
    color: "#9d0028",
    fontSize: responsiveFontSize(12),
    fontWeight: "700",
  },
  inputShell: {
    minHeight: 50,
    flexDirection: "row",
    alignItems: "center",
    gap: responsiveSize(12),
    paddingLeft: responsiveSize(14),
    paddingRight: responsiveSize(8),
    borderWidth: 1,
    borderColor: "#e3bebe",
    borderRadius: responsiveSize(12),
    backgroundColor: "rgba(255, 255, 255, 0.58)",
  },
  input: {
    flex: 1,
    minHeight: 48,
    paddingVertical: responsiveSize(10),
    color: "#161d21",
    fontSize: responsiveFontSize(15),
    fontWeight: "500",
  },
  eyeButton: {
    width: 42,
    height: 42,
    alignItems: "center",
    justifyContent: "center",
  },
  authorizeButton: {
    minHeight: 48,
    marginTop: responsiveSize(4),
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: responsiveSize(8),
    borderRadius: responsiveSize(12),
    backgroundColor: "#c41c3b",
    shadowColor: "#9d0028",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 14,
    elevation: 4,
  },
  authorizeButtonDisabled: {
    opacity: 0.68,
  },
  authorizeButtonText: {
    color: "#ffffff",
    fontSize: responsiveFontSize(15),
    fontWeight: "800",
  },
  notice: {
    marginTop: responsiveSize(8),
    flexDirection: "row",
    gap: responsiveSize(12),
    padding: responsiveSize(16),
    borderWidth: 1,
    borderColor: "rgba(163, 223, 255, 0.34)",
    borderRadius: responsiveSize(16),
    backgroundColor: "rgba(163, 223, 255, 0.12)",
  },
  noticeText: {
    flex: 1,
    color: "#21647f",
    fontSize: responsiveFontSize(12),
    fontWeight: "500",
    lineHeight: responsiveFontSize(18),
    opacity: 0.86,
  },
  securityRow: {
    marginTop: responsiveSize(22),
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: responsiveSize(24),
    opacity: 0.24,
  },
  securityBadge: {
    height: 28,
    minWidth: 36,
    alignItems: "center",
    justifyContent: "center",
  },
  securityDivider: {
    width: 1,
    height: 18,
    backgroundColor: "rgba(22, 29, 33, 0.35)",
  },
  footer: {
    minHeight: 58,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: responsiveSize(10),
    opacity: 0.42,
  },
  footerText: {
    color: "#161d21",
    fontSize: responsiveFontSize(10),
    fontWeight: "800",
    letterSpacing: 1.8,
    textTransform: "uppercase",
  },
});
